INSERT INTO caregiving.user_role(name, description)
    VALUES
      ('erase and update user', 'Erase and update user'),
      ('assign user', 'Assign user'),
      ('delete and edit user', 'Delete and edit user'),
      ('confirm user', 'Confirm user'),
      ('create and multiply user', 'Create and multiply user'),
      ('delete and confirm user', 'Delete and confirm user'),
      ('assign and duplicate user', 'Assign and duplicate user'),
      ('copy and assign user', 'Copy and assign user'),
      ('delete and multiply user', 'Delete and multiply user'),
      ('edit and update user', 'Edit and update user'),
      ('create and copy user', 'Create and copy user'),
      ('delete and compare user', 'Delete and compare user'),
      ('compare and multiply user', 'Compare and multiply user'),
      ('display and multiply user', 'Display and multiply user'),
      ('edit and multiply user', 'Edit and multiply user'),
      ('create and duplicate user', 'Create and duplicate user'),
      ('create and assign user', 'Create and assign user'),
      ('edit and assign user', 'Edit and assign user'),
      ('display and compare user', 'Display and compare user'),
      ('confirm and duplicate user', 'Confirm and duplicate user'),
      ('duplicate user', 'Duplicate user'),
      ('edit and erase user', 'Edit and erase user'),
      ('create and erase user', 'Create and erase user'),
      ('create and update user', 'Create and update user'),
      ('update user', 'Update user'),
      ('copy user', 'Copy user'),
      ('edit and compare user', 'Edit and compare user'),
      ('multiply and update user', 'Multiply and update user'),
      ('assign and multiply user', 'Assign and multiply user'),
      ('duplicate and multiply user', 'Duplicate and multiply user'),
      ('delete and copy user', 'Delete and copy user'),
      ('confirm and erase user', 'Confirm and erase user'),
      ('edit and confirm user', 'Edit and confirm user'),
      ('multiply user', 'Multiply user'),
      ('erase user', 'Erase user'),
      ('compare and confirm user', 'Compare and confirm user'),
      ('edit and copy user', 'Edit and copy user'),
      ('edit and display user', 'Edit and display user'),
      ('copy and update user', 'Copy and update user'),
      ('display and erase user', 'Display and erase user'),
      ('copy and display user', 'Copy and display user'),
      ('erase and duplicate user', 'Erase and duplicate user'),
      ('display and duplicate user', 'Display and duplicate user'),
      ('assign and confirm user', 'Assign and confirm user'),
      ('assign and compare user', 'Assign and compare user'),
      ('copy and erase user', 'Copy and erase user'),
      ('confirm and update user', 'Confirm and update user'),
      ('erase and multiply user', 'Erase and multiply user'),
      ('create and compare user', 'Create and compare user'),
      ('assign and update user', 'Assign and update user'),
      ('compare and update user', 'Compare and update user'),
      ('assign and erase user', 'Assign and erase user'),
      ('display user', 'Display user'),
      ('delete and erase user', 'Delete and erase user'),
      ('duplicate and update user', 'Duplicate and update user'),
      ('display and update user', 'Display and update user'),
      ('copy and duplicate user', 'Copy and duplicate user'),
      ('delete and update user', 'Delete and update user'),
      ('copy and confirm user', 'Copy and confirm user'),
      ('compare user', 'Compare user'),
      ('compare and erase user', 'Compare and erase user'),
      ('copy and multiply user', 'Copy and multiply user'),
      ('delete and duplicate user', 'Delete and duplicate user'),
      ('edit and duplicate user', 'Edit and duplicate user'),
      ('create and display user', 'Create and display user'),
      ('confirm and multiply user', 'Confirm and multiply user'),
      ('delete and display user', 'Delete and display user'),
      ('display and assign user', 'Display and assign user'),
      ('compare and duplicate user', 'Compare and duplicate user'),
      ('create and edit user', 'Create and edit user'),
      ('copy and compare user', 'Copy and compare user'),
      ('create and confirm user', 'Create and confirm user'),
      ('delete and assign user', 'Delete and assign user'),
      ('display and confirm user', 'Display and confirm user'),
      ('create and delete user', 'Create and delete user')
;